# Generated by Django 3.2.12 on 2022-02-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhumtanana', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='abuser',
            name='password',
            field=models.CharField(max_length=25),
        ),
    ]
