# Generated by Django 3.2.12 on 2022-02-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhumtanana', '0003_alter_abuser_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abuser',
            name='is_active',
        ),
    ]
