# Generated by Django 3.2.12 on 2022-02-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dhumtanana', '0004_remove_abuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='abuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
