# Generated by Django 3.2.12 on 2022-02-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dhumtanana', '0005_abuser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abuser',
            old_name='user_name',
            new_name='username',
        ),
    ]
